#!/bin/bash

# The MIT License (MIT)
# 
# Copyright (c) 2014 Phil Dougherty
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

HOSTS="/etc/hosts"
BAK="/etc/hosts.blocked-bak"
USAGE="`basename $0` [-e] [-f filename] [domainname ...] | [-u]"
BLOCK_BEGIN_DELIM="#BLOCK_BEGIN"
BLOCK_END_DELIM="#BLOCK_END"
TMPFILE=.BLOCK_$$_$RANDOM.tmp

error()
{
  if [ -f $TMPFILE ] ; then rm $TMPFILE; fi
  echo "$@" >&2;
  exit 1;
}

#no permissions
if [ `whoami` != "root" ]; then
  error "must be super user (sudo $0 $@)"
fi

#no args
if [ $# -eq 0 ]; then
  error "usage: $USAGE"
fi
    
#unblock
if [ "$1" == "-u" ]; then
  if [ $# -gt 1 ]; then
    error "usage: $USAGE"
  fi
  if [ ! -f $BAK ]; then
    error "not blocked"
  fi
  cat $HOSTS | awk "BEGIN { blocking = 0 } /$BLOCK_BEGIN_DELIM/ { blocking = 1 } blocking != 1 { print } /$BLOCK_END_DELIM/ { blocking = 0 }" > $TMPFILE
  if [ "`diff $TMPFILE $BAK`" = "" ]; then
    cp $BAK $HOSTS
    rm $BAK
    rm $TMPFILE
    exit 0;
  else
    echo "unblocked hosts file does not match bak- manual correction required." >&2
    echo "BAK:" >&2
    cat $BAK >&2
    echo "Unblocked hosts file:" >&2
    cat $TMPFILE >&2
    rm $TMPFILE
    error "aborting..."
  fi
fi

#already blocked
if [ -f $BAK ]; then
  error "already blocked- aborting"
fi

#block
echo $BLOCK_BEGIN_DELIM > $TMPFILE

#from variable
if [ "$1" == "-e" ]; then
  if [ -z "$R2L_NAMES" ]; then
    error "-e : no environment variable \"R2L_NAMES\" found"
  fi
  echo $R2L_NAMES | tr , '\n' | sed "s/http:\/\///" | sed "s/www.//" | awk '{ print "127.0.0.1 " $1 "\n127.0.0.1 www." $1 }' >> $TMPFILE
  shift
fi

#from file
if [ "$1" == "-f" ]; then
  if [ $# -lt 2 ]; then
    error "usage: $USAGE"
  elif [ ! -f $2 ]; then
    error "$2: no such file found"
  fi

  cat $2 | tr , '\n' | sed "s/http:\/\///" | sed "s/www.//" | awk '{ print "127.0.0.1 " $1 "\n127.0.0.1 www." $1 }' >> $TMPFILE
  shift
  shift
fi

#from args
for a in $@; do
   echo $a | sed "s/http:\/\///" | sed "s/www.//" | awk '{ print "127.0.0.1 " $1 "\n127.0.0.1 www." $1 }' >> $TMPFILE
done
echo $BLOCK_END_DELIM >> $TMPFILE

cp $HOSTS $BAK
cat $TMPFILE >> $HOSTS

rm $TMPFILE

exit 0

